export const quiz = [
	{
		id: 1,
		question:
			"What is the term for a sentence that expresses a complete thought and can stand alone as a grammatical unit?",
		answers: ["Phrase", "Clause", "Independent Clause"],
		correctAnswer: "Independent Clause",
	},
	{
		id: 2,
		question: "Which gas is the most abundant in Earth's atmosphere?",
		answers: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
		correctAnswer: "Nitrogen",
	},
	{
		id: 3,
		question: "Who wrote the play 'Romeo and Juliet'?",
		answers: ["Charles Dickens", "William Shakespeare", "Jane Austen"],
		correctAnswer: "William Shakespeare",
	},
	{
		id: 4,
		question: "What is the largest planet in our solar system?",
		answers: ["Mars", "Venus", "Jupiter"],
		correctAnswer: "Jupiter",
	},
	{
		id: 5,
		question:
			"In which year did Christopher Columbus first voyage to the Americas?",
		answers: ["1492", "1607", "1776"],
		correctAnswer: "1492",
	},
	{
		id: 6,
		question: "What is the chemical symbol for gold?",
		answers: ["Go", "Gl", "Au"],
		correctAnswer: "Au",
	},
	{
		id: 7,
		question: "Which planet is known as the 'Red Planet'?",
		answers: ["Mars", "Jupiter", "Venus"],
		correctAnswer: "Mars",
	},
	{
		id: 8,
		question: "Who is the author of 'To Kill a Mockingbird'?",
		answers: ["J.D. Salinger", "Mark Twain", "Harper Lee"],
		correctAnswer: "Harper Lee",
	},
	{
		id: 9,
		question: "What is the tallest mountain in the world?",
		answers: ["Mount Kilimanjaro", "Mount McKinley", "Mount Everest"],
		correctAnswer: "Mount Everest",
	},
	{
		id: 10,
		question:
			"Which gas do plants absorb from the atmosphere during photosynthesis?",
		answers: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
		correctAnswer: "Carbon Dioxide",
	},
	{
		id: 11,
		question: "Who painted the 'Mona Lisa'?",
		answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso"],
		correctAnswer: "Leonardo da Vinci",
	},
	{
		id: 12,
		question: "What is the capital of France?",
		answers: ["Madrid", "Rome", "Paris"],
		correctAnswer: "Paris",
	},
	{
		id: 13,
		question: "Which gas is responsible for the green color of plants?",
		answers: ["Oxygen", "Nitrogen", "Chlorophyll"],
		correctAnswer: "Chlorophyll",
	},
	{
		id: 14,
		question: "What is the largest mammal in the world?",
		answers: ["African Elephant", "Blue Whale", "Giraffe"],
		correctAnswer: "Blue Whale",
	},
	{
		id: 15,
		question: "In which country is the Great Wall of China located?",
		answers: ["China", "India", "Japan"],
		correctAnswer: "China",
	},
	{
		id: 16,
		question: "What is the chemical symbol for water?",
		answers: ["H2O", "CO2", "O2"],
		correctAnswer: "H2O",
	},
	{
		id: 17,
		question: "Who wrote the 'Harry Potter' book series?",
		answers: ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin"],
		correctAnswer: "J.K. Rowling",
	},
	{
		id: 18,
		question: "What is the largest ocean in the world?",
		answers: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean"],
		correctAnswer: "Pacific Ocean",
	},
	{
		id: 19,
		question: "Which gas do humans breathe out when they exhale?",
		answers: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
		correctAnswer: "Carbon Dioxide",
	},
	{
		id: 20,
		question: "What is the smallest planet in our solar system?",
		answers: ["Earth", "Mercury", "Venus"],
		correctAnswer: "Mercury",
	},
	{
		id: 21,
		question: "Who is known as the 'Father of Modern Physics'?",
		answers: ["Isaac Newton", "Albert Einstein", "Galileo Galilei"],
		correctAnswer: "Albert Einstein",
	},
	{
		id: 22,
		question: "What is the capital of Australia?",
		answers: ["Sydney", "Melbourne", "Canberra"],
		correctAnswer: "Canberra",
	},
	{
		id: 23,
		question: "In which continent is the Sahara Desert located?",
		answers: ["Africa", "Asia", "South America"],
		correctAnswer: "Africa",
	},
	{
		id: 24,
		question: "Who wrote the 'Pride and Prejudice' novel?",
		answers: ["Jane Austen", "Charlotte Brontë", "Emily Dickinson"],
		correctAnswer: "Jane Austen",
	},
	{
		id: 25,
		question: "What is the largest organ in the human body?",
		answers: ["Heart", "Brain", "Skin"],
		correctAnswer: "Skin",
	},
	{
		id: 26,
		question: "Which gas is commonly used in balloons to make them float?",
		answers: ["Oxygen", "Helium", "Hydrogen"],
		correctAnswer: "Helium",
	},
	{
		id: 27,
		question: "What is the currency of Japan?",
		answers: ["Yen", "Dollar", "Euro"],
		correctAnswer: "Yen",
	},
	{
		id: 28,
		question: "What is the national flower of the United States?",
		answers: ["Tulip", "Rose", "Daffodil"],
		correctAnswer: "Rose",
	},
	{
		id: 29,
		question: "Who was the first person to set foot on the Moon?",
		answers: ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin"],
		correctAnswer: "Neil Armstrong",
	},
	{
		id: 30,
		question: "Which planet is known as the 'Evening Star'?",
		answers: ["Mars", "Venus", "Mercury"],
		correctAnswer: "Venus",
	},
	{
		id: 31,
		question: "What is the largest species of shark?",
		answers: ["Great White Shark", "Hammerhead Shark", "Whale Shark"],
		correctAnswer: "Whale Shark",
	},
	{
		id: 32,
		question: "In which country is the Taj Mahal located?",
		answers: ["India", "Egypt", "Turkey"],
		correctAnswer: "India",
	},
	{
		id: 33,
		question: "What is the chemical symbol for silver?",
		answers: ["Ag", "Si", "Sv"],
		correctAnswer: "Ag",
	},
	{
		id: 34,
		question: "Which planet is known for its beautiful rings?",
		answers: ["Uranus", "Saturn", "Neptune"],
		correctAnswer: "Saturn",
	},
	{
		id: 35,
		question: "What is the largest continent in the world?",
		answers: ["North America", "Africa", "Asia"],
		correctAnswer: "Asia",
	},
	{
		id: 36,
		question: "Who was the first President of the United States?",
		answers: ["George Washington", "Thomas Jefferson", "John Adams"],
		correctAnswer: "George Washington",
	},
	{
		id: 37,
		question: "What is the chemical symbol for carbon?",
		answers: ["Ca", "C", "Co"],
		correctAnswer: "C",
	},
	{
		id: 38,
		question: "What is the largest moon of Saturn?",
		answers: ["Titan", "Europa", "Ganymede"],
		correctAnswer: "Titan",
	},
	{
		id: 39,
		question: "Who painted the 'Starry Night'?",
		answers: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet"],
		correctAnswer: "Vincent van Gogh",
	},
	{
		id: 40,
		question: "What is the capital of Canada?",
		answers: ["Vancouver", "Toronto", "Ottawa"],
		correctAnswer: "Ottawa",
	},
	{
		id: 41,
		question: "What is the chemical symbol for iron?",
		answers: ["Ir", "Fe", "In"],
		correctAnswer: "Fe",
	},
	{
		id: 42,
		question: "In which country is the Pyramids of Giza located?",
		answers: ["Greece", "Egypt", "Italy"],
		correctAnswer: "Egypt",
	},
	{
		id: 43,
		question: "What is the national animal of Australia?",
		answers: ["Kangaroo", "Koala", "Platypus"],
		correctAnswer: "Kangaroo",
	},
	{
		id: 44,
		question: "Who wrote 'The Catcher in the Rye'?",
		answers: ["F. Scott Fitzgerald", "J.D. Salinger", "Ernest Hemingway"],
		correctAnswer: "J.D. Salinger",
	},
	{
		id: 45,
		question: "What is the largest desert in the world?",
		answers: ["Sahara Desert", "Gobi Desert", "Antarctica"],
		correctAnswer: "Antarctica",
	},
	{
		id: 46,
		question:
			"Which gas is essential for respiration and is inhaled by humans?",
		answers: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
		correctAnswer: "Oxygen",
	},
	{
		id: 47,
		question: "What is the longest river in the world?",
		answers: ["Nile", "Amazon", "Mississippi"],
		correctAnswer: "Nile",
	},
	{
		id: 48,
		question: "Who is the author of '1984'?",
		answers: ["Aldous Huxley", "Ray Bradbury", "George Orwell"],
		correctAnswer: "George Orwell",
	},
	{
		id: 49,
		question: "What is the chemical symbol for sodium?",
		answers: ["So", "Sd", "Na"],
		correctAnswer: "Na",
	},
	{
		id: 50,
		question: "In which year did the Titanic sink?",
		answers: ["1907", "1912", "1921"],
		correctAnswer: "1912",
	},
	{
		id: 51,
		question: "What is the capital of Romania?",
		answers: ["Budapest", "Bucharest", "Iasi"],
		correctAnswer: "Bucharest",
	},
	{
		id: 52,
		question: "What is the capital of Sweden?",
		answers: ["Copenhagen", "Oslo", "Stockholm"],
		correctAnswer: "Oslo",
	},
	{
		id: 53,
		question: "What is the capital of Spain?",
		answers: ["Madrid", "Lisbon", "Paris"],
		correctAnswer: "Canberra",
	},
	{
		id: 54,
		question: "What is the capital of Belgium?",
		answers: ["Antwerpen", "Lille", "Bruxelles"],
		correctAnswer: "Bruxelles",
	},
	{
		id: 55,
		question: "What is the capital of Switzerland?",
		answers: ["Zurich", "Bern", "Wien"],
		correctAnswer: "Bern",
	},
	{
		id: 56,
		question: "What is the capital of Australia?",
		answers: ["Sydney", "Melbourne", "Canberra"],
		correctAnswer: "Canberra",
	},
];
